package transact;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Denzel
 */
public class ChangePass extends javax.swing.JFrame {

    /**
     * Creates new form ChangePass
     */
    Connection con;
    Statement stmt;
    ResultSet rs;

    int curRow = 0;

    public ChangePass() {
        initComponents();
        doConnect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void doConnect() {
        try {
            String host = "jdbc:derby://localhost:1527/LEZNED";
            String uName = "Lezned";
            String pass = "kimi";
            con = DriverManager.getConnection(host, uName, pass);
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String sql = "SELECT * FROM APP.CUSTOMER_DATA";
            rs = stmt.executeQuery(sql);

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(ChangePass.this, err);
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblOld = new javax.swing.JLabel();
        jlblNew = new javax.swing.JLabel();
        jlblNew2 = new javax.swing.JLabel();
        jbtnConfirm = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();
        jpfOld = new javax.swing.JPasswordField();
        jpfNew = new javax.swing.JPasswordField();
        jpfNew2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jlblOld.setText("Old PIN:");

        jlblNew.setText("New PIN:");

        jlblNew2.setText("Re-enter new PIN:");

        jbtnConfirm.setText("Confirm");
        jbtnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConfirmActionPerformed(evt);
            }
        });

        jbtnCancel.setText("Cancel");
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });

        jpfOld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpfOldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jbtnConfirm)
                        .addGap(35, 35, 35)
                        .addComponent(jbtnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblOld)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jpfOld, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblNew2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jpfNew2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblNew)
                                .addGap(4, 4, 4)
                                .addComponent(jpfNew, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jlblOld))
                    .addComponent(jpfOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jlblNew))
                    .addComponent(jpfNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNew2)
                    .addComponent(jpfNew2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnConfirm)
                    .addComponent(jbtnCancel)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConfirmActionPerformed

        int account = 2018001;
        int oldPin = Integer.parseInt(String.valueOf(jpfOld.getPassword()));
        int newPin1 = Integer.parseInt(String.valueOf(jpfNew.getPassword()));
        int newPin2 = Integer.parseInt(String.valueOf(jpfNew2.getPassword()));
        try {
            rs = stmt.executeQuery("SELECT * FROM APP.CUSTOMER_DATA WHERE CARD_NUMBER = " + account);
            rs.first();
            int pin = rs.getInt("PIN");

            if (newPin1 != newPin2) {
                JOptionPane.showMessageDialog(this.jbtnConfirm, "new Pin Does not Match Please Try Again");
            } else if (pin != oldPin) {
                JOptionPane.showMessageDialog(this.jbtnConfirm, "Incorrect old pin Pls try Again");
            } else if ((newPin1 == newPin2) && pin == oldPin) {

                rs.updateInt("PIN", newPin1);
                rs.updateRow();
                JOptionPane.showMessageDialog(this.jbtnConfirm, "Successfully Changed Pin");
            }

            this.dispose();
            new MainMenu().setVisible(true);
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(this.jbtnConfirm, err + " errpr mo tot");
        }
    }//GEN-LAST:event_jbtnConfirmActionPerformed


    private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
        JOptionPane.showMessageDialog(this, "Cancelling Transaction. Please Wait");
        this.dispose();
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_jbtnCancelActionPerformed

    private void jpfOldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpfOldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpfOldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnConfirm;
    private javax.swing.JLabel jlblNew;
    private javax.swing.JLabel jlblNew2;
    private javax.swing.JLabel jlblOld;
    private javax.swing.JPasswordField jpfNew;
    private javax.swing.JPasswordField jpfNew2;
    private javax.swing.JPasswordField jpfOld;
    // End of variables declaration//GEN-END:variables
}
